collections:
  posts:
    output: true
    permalink: /news/:year-:month-:day-:title/
  guides:
    output: true

defaults:
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

permalink: /:title/

plugins:
  - jekyll-mentions